#!/usr/bin/env bash
# Pre-commit hook: auto-generate index.md for every "docs" folder
# Extracts title (first H1) and description (first non-empty line after title)

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# Find all directories named "docs" in the repo
find "$REPO_ROOT" -type d -name "docs" -not -path "*/node_modules/*" -not -path "*/.git/*" | while read -r docs_dir; do
  index_file="$docs_dir/index.md"
  relative_dir="${docs_dir#"$REPO_ROOT"/}"

  # Collect markdown files (exclude index.md itself), sorted by name
  md_files="$(find "$docs_dir" -maxdepth 1 -name "*.md" ! -name "index.md" | sort)"

  [ -z "$md_files" ] && continue

  # Build index content
  {
    echo "# Docs"
    echo ""

    echo "$md_files" | while IFS= read -r filepath; do
      filename="$(basename "$filepath")"

      # Extract title: first line starting with "# "
      title=""
      description=""
      while IFS= read -r line; do
        if [ -z "$title" ]; then
          if [[ "$line" =~ ^#\  ]]; then
            title="${line#\# }"
          elif [ -n "$line" ]; then
            title="$line"
          fi
        elif [ -z "$description" ] && [ -n "$line" ] && [[ ! "$line" =~ ^# ]]; then
          description="$line"
          break
        fi
      done < "$filepath"

      # Fallback: use filename as title
      title="${title:-${filename%.md}}"

      if [ -n "$description" ]; then
        echo "- [${title}](./${filename}) — ${description}"
      else
        echo "- [${title}](./${filename})"
      fi
    done

    echo ""
    echo "<!-- Auto-generated by pre-commit hook. Do not edit. -->"
  } > "$index_file"

  # Stage the updated index
  git add "$index_file"
done
